- hosts: all
  become: true
  roles:
    - basic_pkgs

- hosts: all
  become: true
  roles:
    - user_config

- hosts: all
  become: true
  roles:
<<<<<<< HEAD
    - delete_user

=======
    - create_users
>>>>>>> main
